---
# https://aider.chat/docs/config/aider_conf.html
model: sonnet
read:
  - CONVENTIONS.md
# behavior
cache-prompts: false
check-update: true
multiline: false
notifications: true
show-release-notes: false
stream: false
suggest-shell-commands: false
watch-files: true
yes-always: false
reasoning-effort: high
thinking-tokens: 8k

# git
# Disabled because of: https://github.com/Aider-AI/aider/issues/3049
gitignore: false
auto-commits: false
dirty-commits: false
subtree-only: true

# theme
code-theme: no-clown-fiesta
user-input-color: '#88afa2'
tool-output-color: '#AFAFAF'
tool-error-color: '#984936'
tool-warning-color: '#ab8550'
assistant-output-color: '#BAD7FF'
completion-menu-color: '#E1E1E1'
completion-menu-bg-color: '#202020'
completion-menu-current-color: '#151515'
completion-menu-current-bg-color: '#BAD7FF'
