#!/bin/bash

plugins=(
    golang.go
    golang.go-nightly
    iocave.customize-ui
    iocave.monkey-patch
    ms-azuretools.vscode-docker
    PKief.material-icon-theme
    vscodevim.vim
    zxh404.vscode-proto3
)

code -v > /dev/null
if [[ $? -eq 0 ]];then
    read -r -p "Do you want to install VSC extensions? [y|N] " configresponse
    if [[ $configresponse =~ ^(y|yes|Y) ]];then
        for p in "${plugins[@]}"; do
            code --install-extension "$p"
        done
        echo "Extensions for VSC have been installed. Please restart your VSC."
    else
        echo "Skipping extensions install.";
    fi
else
    echo "It looks like the command 'code' isn't accessible."
    echo "Please make sure you have Visual Studio Code installed"
    echo "And that you executed this procedure: https://code.visualstudio.com/docs/setup/mac"
fi
