#!/usr/bin/env bash

# Yabai configuration file documentantion
# https://github.com/koekeishiya/yabai/wiki/Configuration#configuration-file

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m config debug_output on

# global
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_opacity off
yabai -m config window_border on
yabai -m config window_border_width 5
yabai -m config active_window_border_color 0xffbe95ff
yabai -m config normal_window_border_color 0xff525252

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# system floating windows
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title='Preferences$' manage=off topmost=on
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add title="Software Update$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add title='Archive Utility$' manage=off
yabai -m rule --add title='Bin$' manage=off
yabai -m rule --add title="^Opening*" manage=off

# 3rd party
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^Hidden Bar$" manage=off
yabai -m rule --add app="^Amphetamine$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Spaceman$" manage=off
yabai -m rule --add app="^Steam$" manage=off

echo "yabai configuration loaded.."
