#!/usr/bin/env bash


# Yabai configuration file documentantion
# https://github.com/koekeishiya/yabai/wiki/Configuration#configuration-file


# ========== Signals ========== #

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# ========== Debug ========== #

yabai -m config debug_output on


# ========== Layout ========== #

# bsp or float (default: bsp)
yabai -m config layout bsp

# Override default layout for space 2 only
# yabai -m config --space 2 layout float

# New window spawns to the left if vertical split, or top if horizontal split
# yabai -m config window_placement first_child

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child


# ========== Padding and Gaps ========== #

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# Override gaps for space 2 only
# yabai -m config --space 2 window_gap 5


# ========== Padding and Gaps ========== #

# on or off (default: off)
# yabai -m config auto_balance off

# Floating point value between 0 and 1 (default: 0.5)
# yabai -m config split_ratio 0.5


# ========== Mouse Support ========== #

# set mouse interaction modifier key (default: fn)
# yabai -m config mouse_modifier fn

# set modifier + left-click drag to resize window (default: move)
# yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
# yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
# yabai -m config focus_follows_mouse autofocus

# set mouse follows focus mode (default: off)
# yabai -m config mouse_follows_focus off


# ========== Window Modifications ========== #

# floating windows are always on top (default: off)
# yabai -m config window_topmost on

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow off

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

# window border settings
yabai -m config window_border off
yabai -m config window_border_width 4
yabai -m config active_window_border_color 0xfff5f5f5
yabai -m config normal_window_border_color 0xff737373
yabai -m config insert_feedback_color 0xff737373
yabai -m config active_window_border_topmost on

# ========== Status Bar ========== #

# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
# yabai -m config external_bar main:20:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
# yabai -m config external_bar all:20:20


# ========== Rules ========== #

# system floating windows
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add title="Software Update$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add title='Archive Utility$' manage=off
yabai -m rule --add title='Bin$' manage=off

# 3rd party
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^Hidden Bar$" manage=off
yabai -m rule --add app="^Amphetamine$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add title="^Opening*" manage=off


# ========== Other ========== #

# fix folders opened from deskto not tiling
defaults write com.apple.finder DisableAllAnimations -bool true
killall Finder # or logout and login

# to reset system defaults, delete the key instead
# defaults delete com.apple.finder DisableAllAnimations


echo "yabai configuration loaded.."
