#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config debug_output on

# global
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_opacity off
yabai -m config window_border off
yabai -m config window_border_width 1
yabai -m config window_border_radius 12
yabai -m config window_border_hidpi off
yabai -m config window_border_blur off
yabai -m config active_window_border_color 0xffa5d6ff
yabai -m config normal_window_border_color 0xff373737

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

# system floating windows
# yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add title="Software Update$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add title='Archive Utility$' manage=off
yabai -m rule --add title='Bin$' manage=off
yabai -m rule --add title="^Opening*" manage=off

# 3rd party
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^Hidden Bar$" manage=off
yabai -m rule --add app="^Amphetamine$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Spaceman$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^OpenVPN Connect$" manage=off

echo "yabai configuration loaded.."
